version: "3.8"

services:
    jenkins-server:
        image: jenkins/jenkins:lts-jdk11
        container_name: placeet-jenkins-dev
        ports:
            - "8080:8080"
    db-dev:
        image: postgres:13.1
        container_name: placeet-db-dev
        restart: always
        logging:
            options:
              max-size: "10m"
              max-file: "3"
        environment:
            POSTGRES_USER: ${DB_USER_DEV}
            POSTGRES_PASSWORD: ${DB_PASSWORD_DEV}
            POSTGRES_DB: ${DB_DEV}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./db_dev:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    api-dev:
        build:
            context: "./"
            dockerfile: Dockerfile-dev
        container_name: placeet-api-dev
        restart: always
        logging:
            options:
              max-size: "10m"
              max-file: "3"
        volumes:
            - .:/usr/app
        depends_on:
            - db-dev
        environment:
            - NODE_ENV=development
    server-dev:
        build:
            context: "./nginx/"
            dockerfile: Dockerfile-dev
        container_name: placeet-server-dev
        hostname: placeet-server-dev
        restart: always
        logging:
            options:
              max-size: "10m"
              max-file: "3"
        ports:
            - "80:80"
        depends_on:
            - api-dev