version: "3.8"

services:
    db:
        image: postgres
        container_name: placeet-db
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - /custom/mount:/var/lib/postgresql/data
    api:
        build: "./"
        container_name: placeet-api
        restart: always
        volumes:
            - .:/usr/app
        depends_on:
            - db
    nginx:
        build: "./nginx/"
        container_name: placeet-server
        restart: always
        volumes:
            - ./nginx/certs:/etc/nginx/certs
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - api