version: "3.8"

services:
    db:
        image: postgres
        container_name: placeet-db
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./db:/var/lib/postgresql/data
    api:
        build:
            context: "./"
            dockerfile: Dockerfile-prod
        container_name: placeet-api
        restart: always
        volumes:
            - .:/usr/app
        depends_on:
            - db
    server:
        build:
            context: "./nginx/"
            dockerfile: Dockerfile-prod
        container_name: placeet-server
        hostname: placeet-server
        restart: always
        volumes:
            - /etc/letsencrypt:/etc/nginx/letsencrypt
            - /var/www/placeet:/var/www/placeet
        ports:
            - "8081:80"
        depends_on:
            - api